---
- name: Download WordPress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/var/www/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"

- name: Remove existing dir contents
  file: path=/var/www/html/index.nginx-debian.html state=absent

- name: Extract archive
  command: chdir=/var/www /bin/tar xvf wordpress-{{ wp_version }}.tar.gz -C html

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/var/www/html/

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no

- name: Copy WordPress config file
  template: src=wp-config.php dest=/var/www/html/

- name: Change ownership of WordPress installation
  file: path=/var/www/html/ owner=wordpress group=wordpress state=directory recurse=yes
