---
- name: Create blueprint server
  hosts: local
  connection: local
  gather_facts: False
  vars_files:  
    - vars.yml
  tasks:
    
    - name: Provision server
      rax:
        credentials: "{{ pyrax_creds_file }}" 
        region: "{{ region }}"
        name: blueprint
        auto_increment: no
        flavor: "{{ server_flavor }}"
        image: "{{ server_image }}"
        key_name: "{{ server_keypair }}"
        wait: yes
        state: present
        group: blueprint
      register: rax_blueprint

    - name: Add server to host
      add_host:
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.rax_accessipv4 }}"
        groupname: blueprint
      with_items: rax_blueprint.success
      when: rax_blueprint.action == 'create'

- name: Provision DB infrastructure
  hosts: local
  connection: local
  gather_facts: False
  vars_files:
    - vars.yml
  roles:
    - db-deploy

- name: Configure server and create image
  hosts: blueprint
  remote_user: root
  vars_files:
    - vars.yml
    - creds.yml
  vars:
    rackspace_username: "{{ username }}"
    rackspace_apikey: "{{ api_key }}"
    cloud_monitoring_agent_force_setup: True
    cloud_monitoring_filesystem_alarm: True
    cloud_monitoring_cpu_alarm: True
    cloud_monitoring_memory_alarm: True
    cloud_monitoring_load_alarm: True
    notification_plan_id: "{{ lookup('file', 'roles/arch-deploy/files/.np_id') }}"
    wp_db_host: "{{ hostvars.localhost.cdb.cdb.hostname }}"
    server_hostname: "{{ dns_domain }}"
  roles:
    - { role: cloud-monitoring-agent, tags: ['monitoring'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: php-fpm, tags: ['php-fpm'] }
    - { role: wordpress, tags: ['wordpress'] }

